### PR TITLE
add support for patch request

### PR DESCRIPTION
**Pull request by ffoysal**
many rest api developer needs PATCH request as well

### CODE REVIEW

**Comment by ffoysal** [comment]
@jeffbski Can I get your feedback on this.

**Comment by jeffbski** [comment]
@ffoysal this looks excellent! Thanks for submitting this PR. 

Also if you would like, I'd be happy to add you as a contributor to this project, you did a great job with this PR.

**Comment by jeffbski** [comment]
@ffoysal I meant collaborator not contributor, so you can actually push changes too.

**Comment by ffoysal** [comment]
Sure @jeffbski  I would love to be contributor/collaborator

**Comment by jeffbski** [comment]
Fantastic! I have added you now. It should be in your inbox. @ffoysal

**Comment by ffoysal** [comment]
I just did npm install bench-rest but cannot see the updated code there, whats need to be done for that ?

**Comment by jeffbski** [comment]
oops. I need to publish it to npm. will do that now and see about adding you as collaborator to that too.

**Comment by jeffbski** [comment]
ok, it is published now in npm v1.2.4 sorry for the confusion.

**Comment by jeffbski** [comment]
@ffoysal Do you have an account on npmjs.org? If so I can add you as a collaborator so you could push releases to npm as well.

**Comment by ffoysal** [comment]
Thanks for publishing @jeffbski my user name in npmjs is ffoysal

**Comment by jeffbski** [comment]
Alright, I've added you as a collaborator there too, so if you ever need to do a publish you can do so. 

I've added some developer notes to the readme here https://github.com/jeffbski/bench-rest#developer-notes if you need to publish a new version. Feel free to ask me if any questions. 

Thanks and have a great weekend!

**Pull request merged**
